### ISSUE TITLE
Add-on's demo code has a bug

### ISSUE THREAD

**Issue by johannest** [vaadin-component-factory/popup#13]
It is: 
`Button button = new Button("Show/Hide");
    button.addClickListener(e -> {
        if (popup.isOpened()) {
            popup.hide();
        } else {
            popup.show();
        }
    });`
But should be e.g.:
`button.addClickListener(e -> {
            if (!popup.isOpened()) {
                popup.hide();
            } else {
                popup.show();
            }
        });`

**Comment by johannest** [comment]
in README

**Comment by johannest** [comment]
Also would be good to add `add(button, popup);` so it would be clear that both button and popup need to added to same layout

**Comment by bwajtr** [comment]
The demo has been redone considerably since then... closing this issue
