### ISSUE TITLE
Popup content doesn't work properly when it is used in Grid HeaderRow

### ISSUE THREAD

**Issue by hoshie82** [vaadin-component-factory/popup#16]
In the original code I work with tabs, but the behaviour is quite similar to the used button, because the grid is attached/detached when switching the tabs...
If you attach the grid the first time, everything is fine and the popup is shown with the correct css properties. If you remove the grid and add it again, the popup content is inserted directly in the shadow-root of the '&lt;div part="content"&gt;' instead of the overlay-element. Also the css can not be read anymore, because it is hidden by the shadow-root element.

I have no idea, why this happens and how to fix it... any suggestions or workarounds?! Is this a bug? A bug in the popup-component or the vaadin grid?!

screenshots:
dom, when grid is shown first time
![screenshot](https://i.imgur.com/S7rkEEW.jpg)

dom, when grid was detached and attached again
![screenshot](https://i.imgur.com/fyQBOVx.jpeg)

MyCustomComponent.java
````
    @Tag("my-custom-component")
    @CssImport("./components/my-custom-component.css")
    public class MyCustomComponent extends Div {

        public MyCustomComponent() {
            super();
            add(new Text("test"));
        }
    }
````
my-custom-component.css
````
my-custom-component {
  background-color: red;
  width: 400px;
  height: 300px;
  display: block;
}
````

````
    private Component buildContent() {
        Grid<String> content = new Grid<>();
        content.addColumn(ValueProvider.identity()).setKey("column").setHeader(createPopupComponent());
        content.setItems(List.of("1", "2", "3"));

        Button b = new Button("click me");
        Div container = new Div(b);
        b.addClickListener(e -> {
            if (content.isAttached()) {
                container.remove(content);
            } else {
                container.add(content);
            }
        });
        return container;
    }


    private static Div createPopupComponent() {
        String id = "popup-button-id";
        Button b = new Button("show popup");
        b.setId(id);

        Popup popup = new Popup();
        popup.add(new MyCustomComponent());
        popup.setFor(id);
        return new Div(b, popup);
    }

`````

vaadin version: 23.1.7

**Comment by TatuLund** [comment]
> because the grid is attached/detached when switching the tabs...

It may be that this is not an issue in Popup, but in Grid. Grid with components in headers or component rendered cells is a complex beast. If you detach it, I tend to think in edge cases it is better to generate a new Grid instance instead of attaching the old one.

Also what solution you are using for switching tabs? Just asking as the framework does not yet have TabSheet component.

I would recommend you to check this add-on

https://vaadin.com/directory/component/tabsheet

This version of TabSheet does not detach, but just hides the sheets that or not currently shown. Thus I think it could work better in your use case.

There is development ongoing to include similar component in the framework. It wont be in 23.2 which is released today, but some future version.

**Comment by hoshie82** [comment]
... I almost wrote my own grid-component to have a filter row with filter fields (I use the popup for complex filtering), to hide and show header/footer rows, toggle column visibility, ... ^^ The vaadin grid is not my favourite component... 

I also wrote an own tabsheet class with vaadin Tabs / Tab components, that replaces the current shown tab with the selected tab...

I'm not sure, if that addon is a good alternative, because we're using quite complex components for the tabs (with other nested tabsheets), and the performance already is a large bottle neck at the moment. If I'll blow up the dom and push all components to it, it will become even slower... ?! 

(But I'll take a look... thx.)

Btw: the workaround from #3 seems to work. Saw this issue after publishing this one ... Now I create a new popup every time in the onAttach method and remove the old one... It's not the best solution I'd like to have, but who cares.. ^^
