### ISSUE TITLE
Compatibility for Vaadin 24

### ISSUE THREAD

**Issue by nbabb** [vaadin-component-factory/popup#17]
I'm trying the Vaadin 24.0.0.rc1 build and am getting the following errors

Cannot access 'com.vaadin.flow.component.polymertemplate.PolymerTemplate' which is a supertype of 'com.vaadin.componentfactory.Popup'. Check your module classpath for missing or conflicting dependencies

Is this component compatible with Vaadin 24?  Thanks.

**Comment by TatuLund** [comment]
> Is this component compatible with Vaadin 24? Thanks.

Not currently. Some changes are needed as PolymerTemplate class has been removed from Vaadin 24.

**Comment by eidottermihi** [comment]
Is there some way one could help? I looked into the current implementation and found that its depending on https://www.npmjs.com/package/@vaadin-component-factory/vcf-popup which uses Polymer 3.

So my guess would be that this NPM library must first be updated to use Lit ?

**Comment by TatuLund** [comment]
> So my guess would be that this NPM library must first be updated to use Lit ?

No, that is not needed. The problem is about deprecated Java class that was removed in Vaadin 24. Underlying Polymer 3 libraries have not been removed in Vaadin 24 as all Vaadin's web-components still use them.

**Comment by leangermany** [comment]
Hi, do you have any timeline for updating this addon? 
We would really appreciate an version without PolymerTemplate.

**Comment by leangermany** [comment]
Version 4.0.0 is released: "Updates to make component compatible with Vaadin 24." Thanks

**Comment by eidottermihi** [comment]
@TatuLund do you mind sharing where the source for version 4.0.0 comes from? apparently it does not seem to be this repository?

**Comment by TatuLund** [comment]
It is in different branch https://github.com/vaadin-component-factory/popup/tree/v24
