### ISSUE TITLE
Component not working on Grid header & Preserve on refresh

### ISSUE THREAD

**Issue by paodb** [vaadin-component-factory/popup#3]
Hello. I was trying to add this component to a column header in a Grid in a view that has @PreserveOnRefresh and when I refresh the page the popup is no longer visible when I click on the button. Here's a small example to test this:

```java
   	Grid<String> grid = new Grid<>();    	
    	add(grid);
      	Button button = new Button((new Icon(VaadinIcon.FILTER)));
    	button.setId("button-id");
    	Popup popup = new Popup();
    	popup.setFor(button.getId().orElse(null));
    	popup.add(new Span("Test")); 
    	Div popupDiv = new Div(button, popup);       	
//    	add(popupDiv);    	    	
    	grid.addColumn(x -> x).setHeader(popupDiv);
```

This example works fine when @PreserveOnRefresh is disabled, and also when adding the popupDiv directly to the Grid regardless the annotation is enabled.

Any idea of why is this happening? Thanks.

**Comment by TatuLund** [comment]
I can easily replicate the problem. I first thought that moving connected callback to onAttach would help, but it is not solving the problem.

**Comment by TatuLund** [comment]
I found a workaround however.

If you add onAttach into your component or view where Popup is used and re-create / populate the component onAttach event, it will work

```
    @Override
    protected void onAttach(AttachEvent onAttach) {
        popup = new Popup();
        popup.setFor("columnsbutton");
        content.add(popup);
        addColumnSelectorMenu(expensesGrid);
    }
```

**Comment by TatuLund** [comment]
I found a fix. I will release a new version soon.

**Comment by TatuLund** [comment]
Version 2.2.2 released in the Directory

**Comment by paodb** [comment]
Thanks for the quick fix!
